"""
Django settings for sysgov_project project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Adicione o caminho do projeto ao sys.path para que o Python possa encontrar os apps aninhados.
# Isso resolve o ModuleNotFoundError para apps aninhados.
sys.path.insert(0, os.path.join(BASE_DIR, 'sysgov_project'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-**hfe%*hy@gn9r2wbgo^e)qj&yj$48)xr5iiq$h%4v851m6ui*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ckeditor',

    # Apps do Allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',

    # SEUS APPS PERSONALIZADOS:
    # Use o nome simples para a estrutura que você tem.
    'core',
    'contratacoes',
    'financeiro',
    'licitacoes',
    'integracao_audesp',
    'widget_tweaks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'sysgov_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Aponta para a pasta 'templates' dentro do 'core' para encontrar o 'base.html'
        'DIRS': [os.path.join(BASE_DIR, 'core', 'templates')],
        'APP_DIRS': True, # Procura templates em cada app
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request', # **Obrigatório para Allauth**
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Corrigido o nome do context processor, se for o que você tem
                'core.context_processors.global_context', # Se você tem um context processor global, mantenha
            ],
        },
    },
]

# SysGov_Project/sysgov_project/settings.py

# ... (outras configurações) ...

# ----------------------------------------------------
# Configurações do Django Allauth (Versão Final e Robusta)
# ----------------------------------------------------

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

SITE_ID = 1

# Define como os usuários podem fazer login: APENAS por username.
# ACCOUNT_LOGIN_METHODS = ['username']

# Garante que o nome de usuário seja sempre requerido e único.
# ACCOUNT_USERNAME_REQUIRED = True
# ACCOUNT_USERNAME_UNIQUE = True

# O e-mail é necessário para o cadastro.
# ACCOUNT_EMAIL_REQUIRED = True

# A verificação de e-mail é desativada para simplificar.
# ACCOUNT_EMAIL_VERIFICATION = 'none'

# FORÇA O USO DO FORMULÁRIO DE LOGIN PADRÃO DO ALLAUTH
# Esta é a linha que garante que o campo de senha será sempre renderizado.
# ACCOUNT_FORMS = {
#     'login': 'allauth.account.forms.LoginForm',
# }

# Define os campos que aparecem no formulário de cadastro (signup).
# ACCOUNT_SIGNUP_FIELDS = ['username', 'email']

# Redireciona para a página inicial ('home') após o login e logout.
LOGIN_REDIRECT_URL = 'core:home'
LOGIN_REDIRECT_URL = 'core:home'

# ----------------------------------------------------
# Fim das Configurações do Django Allauth
# ----------------------------------------------------


WSGI_APPLICATION = 'sysgov_project.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    { 'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator', },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
LANGUAGE_CODE = 'pt-BR'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'core', 'static'),
]

# Media files (user uploads)
MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'mediafiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'