# Generated by Django 5.2.4 on 2025-09-04 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título descritivo do Estudo Técnico Preliminar.', max_length=255, verbose_name='Título do ETP')),
                ('numero_processo', models.CharField(help_text='Número do processo administrativo relacionado a este ETP.', max_length=50, unique=True, verbose_name='Número do Processo SEI/Interno')),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('setor_demandante', models.CharField(help_text='Nome do setor que solicitou a contratação.', max_length=100, verbose_name='Setor Demandante')),
                ('descricao_necessidade', models.TextField(help_text='Detalhe o problema a ser resolvido ou a necessidade.', verbose_name='1. Descrição da Necessidade')),
                ('objetivo_contratacao', models.TextField(help_text='Qual o resultado esperado com a contratação?', verbose_name='2. Objetivo da Contratação')),
                ('requisitos_contratacao', models.TextField(help_text='Características mínimas que a solução deve ter.', verbose_name='3. Requisitos da Contratação')),
                ('levantamento_solucoes_mercado', models.TextField(help_text='Pesquisa e análise das alternativas disponíveis no mercado.', verbose_name='4. Levantamento de Soluções de Mercado')),
                ('estimativa_quantidades', models.TextField(help_text='Qual a quantidade/dimensão da contratação.', verbose_name='5. Estimativa das Quantidades')),
                ('estimativa_valor', models.DecimalField(blank=True, decimal_places=2, help_text='Valor estimado da contratação.', max_digits=15, null=True, verbose_name='6. Estimativa do Valor da Contratação (R$)')),
                ('resultados_esperados', models.TextField(help_text='Benefícios que a contratação trará.', verbose_name='7. Resultados Esperados')),
                ('viabilidade_justificativa_solucao', models.TextField(help_text='Qual a melhor solução e por que é a melhor.', verbose_name='8. Viabilidade e Justificativa da Solução Escolhida')),
                ('contratacoes_correlatas', models.TextField(blank=True, help_text='Essa contratação depende de outras?', null=True, verbose_name='9. Contratações Correlatas e/ou Interdependentes')),
                ('alinhamento_planejamento', models.TextField(help_text='A contratação está de acordo com os objetivos maiores da instituição?', verbose_name='10. Alinhamento com o Planejamento Estratégico')),
                ('status', models.CharField(choices=[('EM_ELABORACAO', 'Em Elaboração'), ('AGUARDANDO_REVISAO', 'Aguardando Revisão'), ('REVISADO', 'Revisado'), ('APROVADO', 'Aprovado'), ('RECUSADO', 'Recusado'), ('CANCELADO', 'Cancelado')], default='EM_ELABORACAO', max_length=30, verbose_name='Status do Documento')),
                ('observacoes_analise', models.TextField(blank=True, null=True, verbose_name='Observações da Análise')),
            ],
            options={
                'verbose_name': 'Estudo Técnico Preliminar (ETP)',
                'verbose_name_plural': 'Estudos Técnicos Preliminares (ETP)',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ItemCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_padronizado', models.CharField(help_text='Nome comum e padronizado do bem ou serviço no catálogo.', max_length=255, unique=True, verbose_name='Nome Padronizado do Item')),
                ('descricao_tecnica', models.TextField(help_text='Especificações técnicas, características físicas, normas aplicáveis. (Use um editor WYSIWYG se possível).', verbose_name='Descrição Técnica Detalhada')),
                ('unidade_medida', models.CharField(help_text='Ex: UN (Unidade), KG (Quilograma), M2 (Metro Quadrado), HORA (Hora).', max_length=50, verbose_name='Unidade de Medida')),
                ('preco_historico_medio', models.DecimalField(blank=True, decimal_places=2, help_text='Média dos preços de contratações anteriores.', max_digits=15, null=True, verbose_name='Preço Histórico Médio (R$)')),
                ('data_ultima_atualizacao', models.DateField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Item de Catálogo',
                'verbose_name_plural': 'Itens de Catálogo',
                'ordering': ['nome_padronizado'],
            },
        ),
        migrations.CreateModel(
            name='ItemPCA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_item', models.CharField(help_text="Código ou descrição que identifica o item no PCA (Ex: 'SERVIÇO-TI-001', 'MAT-ESC-005').", max_length=100, unique=True, verbose_name='Identificador do Item no PCA')),
                ('descricao_item', models.TextField(help_text='Descrição detalhada do item a ser contratado/adquirido conforme o PCA.', verbose_name='Descrição do Item')),
                ('valor_estimado_pca', models.DecimalField(decimal_places=2, help_text='Valor previsto para a contratação/aquisição no PCA.', max_digits=15, verbose_name='Valor Estimado no PCA (R$)')),
                ('unidade_requisitante', models.CharField(help_text='Unidade que previu a demanda por este item no PCA.', max_length=100, verbose_name='Unidade Requisitante Prevista')),
            ],
            options={
                'verbose_name': 'Item do PCA',
                'verbose_name_plural': 'Itens do PCA',
                'ordering': ['identificador_item'],
            },
        ),
        migrations.CreateModel(
            name='ModeloTexto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('texto', models.TextField()),
            ],
            options={
                'verbose_name': 'Modelo de Texto',
                'verbose_name_plural': 'Modelos de Texto',
            },
        ),
        migrations.CreateModel(
            name='ParecerTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Parecer Técnico',
                'verbose_name_plural': 'Pareceres Técnicos',
            },
        ),
        migrations.CreateModel(
            name='PCA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_vigencia', models.IntegerField(help_text='Ano ao qual este Plano de Contratações Anual se refere (Ex: 2025).', unique=True, verbose_name='Ano de Vigência')),
                ('data_aprovacao', models.DateField(help_text='Data em que o PCA foi formalmente aprovado.', verbose_name='Data de Aprovação do PCA')),
                ('arquivo_pca', models.FileField(blank=True, null=True, upload_to='pca_arquivos/', verbose_name='Arquivo PCA Completo (PDF)')),
                ('titulo', models.CharField(default='PCA', max_length=255, verbose_name='Título do PCA')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição do PCA')),
            ],
            options={
                'verbose_name': 'Plano de Contratações Anual (PCA)',
                'verbose_name_plural': 'Planos de Contratações Anuais (PCA)',
                'ordering': ['-ano_vigencia'],
            },
        ),
        migrations.CreateModel(
            name='PesquisaPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornecedor', models.CharField(max_length=255)),
                ('valor_cotado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_pesquisa', models.DateField()),
            ],
            options={
                'verbose_name': 'Pesquisa de Preço',
                'verbose_name_plural': 'Pesquisas de Preço',
            },
        ),
        migrations.CreateModel(
            name='RequisitoPadrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Requisito Padrão',
                'verbose_name_plural': 'Requisitos Padrão',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='TR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título descritivo do Termo de Referência.', max_length=255, verbose_name='Título do Termo de Referência')),
                ('numero_processo', models.CharField(help_text='Número do processo administrativo relacionado a este TR.', max_length=50, unique=True, verbose_name='Número do Processo SEI/Interno')),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('objeto', models.TextField(help_text='Descrição clara e concisa do que será contratado.', verbose_name='1. Objeto')),
                ('justificativa', models.TextField(help_text='Relembre a necessidade e os objetivos da contratação.', verbose_name='2. Justificativa')),
                ('especificacoes_tecnicas', models.TextField(help_text='Detalhe as características técnicas do bem ou serviço.', verbose_name='3. Especificações Técnicas do Objeto')),
                ('metodologia_execucao', models.TextField(blank=True, help_text='Como o serviço deve ser executado.', null=True, verbose_name='4. Metodologia de Execução (se serviço)')),
                ('prazo_execucao_entrega', models.CharField(help_text='Quando o bem deve ser entregue ou o serviço concluído.', max_length=255, verbose_name='5. Prazo de Execução/Entrega')),
                ('cronograma_fisico_financeiro', models.TextField(blank=True, help_text='Detalhe das etapas e dos pagamentos.', null=True, verbose_name='6. Cronograma Físico-Financeiro (se aplicável)')),
                ('criterios_habilitacao', models.TextField(help_text='Requisitos que a empresa precisa comprovar.', verbose_name='7. Critérios de Habilitação (Técnica)')),
                ('criterios_aceitacao', models.TextField(help_text='Como a administração vai verificar se o que foi entregue está de acordo.', verbose_name='8. Critérios de Aceitação do Objeto')),
                ('criterios_pagamento', models.TextField(help_text='Como e quando os pagamentos serão feitos.', verbose_name='9. Critérios de Pagamento')),
                ('obrigacoes_partes', models.TextField(help_text='O que cada parte deve fazer.', verbose_name='10. Obrigações da Contratada e da Contratante')),
                ('sancoes_administrativas', models.TextField(help_text='Quais as penalidades em caso de descumprimento.', verbose_name='11. Sanções Administrativas')),
                ('fiscalizacao_contrato', models.TextField(help_text='Quem será o fiscal do contrato e suas atribuições.', verbose_name='12. Fiscalização do Contrato')),
                ('vigencia_contrato', models.CharField(help_text='Por quanto tempo o contrato será válido.', max_length=255, verbose_name='13. Vigência do Contrato')),
                ('estimativa_preco_tr', models.DecimalField(blank=True, decimal_places=2, help_text='Valor estimado da contratação para o TR.', max_digits=15, null=True, verbose_name='14. Estimativa de Preço (R$)')),
                ('status', models.CharField(choices=[('EM_ELABORACAO', 'Em Elaboração'), ('AGUARDANDO_REVISAO', 'Aguardando Revisão'), ('REVISADO', 'Revisado'), ('APROVADO', 'Aprovado'), ('RECUSADO', 'Recusado'), ('CANCELADO', 'Cancelado')], default='EM_ELABORACAO', max_length=20, verbose_name='Status do TR')),
                ('observacoes_analise', models.TextField(blank=True, help_text='Comentários e feedback da equipe de análise.', null=True, verbose_name='Observações da Análise')),
            ],
            options={
                'verbose_name': 'Termo de Referência (TR)',
                'verbose_name_plural': 'Termos de Referência (TR)',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(max_length=50, verbose_name='Número do Contrato')),
                ('ano_contrato', models.IntegerField(verbose_name='Ano do Contrato')),
                ('objeto', models.TextField(verbose_name='Objeto do Contrato')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Total do Contrato (R$)')),
                ('data_assinatura', models.DateField(verbose_name='Data de Assinatura')),
                ('data_inicio_vigencia', models.DateField(verbose_name='Início da Vigência')),
                ('data_fim_vigencia', models.DateField(verbose_name='Fim da Vigência')),
                ('status', models.CharField(choices=[('VIGENTE', 'Vigente'), ('ENCERRADO', 'Encerrado'), ('CANCELADO', 'Cancelado')], default='VIGENTE', max_length=20, verbose_name='Status do Contrato')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('contratado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='core.fornecedor', verbose_name='Fornecedor Contratado')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-ano_contrato', '-numero_contrato'],
            },
        ),
    ]
