# Generated by Django 5.2.4 on 2025-09-04 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratacoes', '0001_initial'),
        ('core', '0001_initial'),
        ('licitacoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='licitacao_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_gerados', to='licitacoes.edital', verbose_name='Licitação de Origem'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='processo_vinculado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='core.processo', verbose_name='Processo Vinculado'),
        ),
        migrations.AddField(
            model_name='etp',
            name='anexos',
            field=models.ManyToManyField(blank=True, to='core.arquivoanexo', verbose_name='Anexos do ETP'),
        ),
        migrations.AddField(
            model_name='etp',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Elaborador'),
        ),
        migrations.AddField(
            model_name='etp',
            name='processo_vinculado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etp_documento', to='core.processo', verbose_name='Processo Principal (ProGestor Público)'),
        ),
        migrations.AddField(
            model_name='etp',
            name='item_pca_vinculado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contratacoes.itempca', verbose_name='Item do PCA Vinculado'),
        ),
        migrations.AddField(
            model_name='parecertecnico',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parecertecnico',
            name='etp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pareceres', to='contratacoes.etp'),
        ),
        migrations.AddField(
            model_name='pca',
            name='responsavel_aprovacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Responsável pela Aprovação'),
        ),
        migrations.AddField(
            model_name='itempca',
            name='pca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='contratacoes.pca', verbose_name='Plano de Contratações Anual'),
        ),
        migrations.AddField(
            model_name='pesquisapreco',
            name='etp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesquisas_preco', to='contratacoes.etp'),
        ),
        migrations.AddField(
            model_name='tr',
            name='anexos',
            field=models.ManyToManyField(blank=True, help_text='Anexos relevantes para este Termo de Referência.', to='core.arquivoanexo', verbose_name='Anexos do TR'),
        ),
        migrations.AddField(
            model_name='tr',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Elaborador'),
        ),
        migrations.AddField(
            model_name='tr',
            name='etp_origem',
            field=models.OneToOneField(help_text='Estudo Técnico Preliminar que deu origem a este Termo de Referência.', on_delete=django.db.models.deletion.CASCADE, related_name='termo_referencia', to='contratacoes.etp', verbose_name='ETP de Origem'),
        ),
        migrations.AddField(
            model_name='tr',
            name='processo_vinculado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tr_documento', to='core.processo', verbose_name='Processo Principal (ProGestor Público)'),
        ),
        migrations.AlterUniqueTogether(
            name='contrato',
            unique_together={('numero_contrato', 'ano_contrato')},
        ),
        migrations.AlterUniqueTogether(
            name='itempca',
            unique_together={('pca', 'identificador_item')},
        ),
    ]
