# Generated by Django 5.2.4 on 2025-09-05 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratacoes', '0002_initial'),
        ('core', '0001_initial'),
        ('licitacoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtaRegistroPrecos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ata', models.CharField(max_length=50, verbose_name='Número da Ata')),
                ('ano_ata', models.IntegerField(verbose_name='Ano da Ata')),
                ('objeto', models.TextField(verbose_name='Objeto da Ata de RP')),
                ('valor_total_registrado', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Total Registrado (R$)')),
                ('data_assinatura', models.DateField(verbose_name='Data de Assinatura')),
                ('data_inicio_vigencia', models.DateField(verbose_name='Início da Vigência')),
                ('data_fim_vigencia', models.DateField(verbose_name='Fim da Vigência')),
                ('status', models.CharField(choices=[('VIGENTE', 'Vigente'), ('EXPIRADA', 'Expirada'), ('CANCELADA', 'Cancelada')], default='VIGENTE', max_length=20, verbose_name='Status da Ata')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('fornecedor_beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atas_rp', to='core.fornecedor', verbose_name='Fornecedor Beneficiário')),
                ('licitacao_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atas_geradas', to='licitacoes.edital', verbose_name='Licitação de Origem')),
                ('processo_vinculado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atas_rp', to='core.processo', verbose_name='Processo Vinculado')),
            ],
            options={
                'verbose_name': 'Ata de Registro de Preços',
                'verbose_name_plural': 'Atas de Registro de Preços',
                'ordering': ['-ano_ata', '-numero_ata'],
                'unique_together': {('numero_ata', 'ano_ata')},
            },
        ),
    ]
