# Generated by Django 5.2.4 on 2025-09-02 13:57

from django.db import migrations

def atualizar_status_para_frente(apps, schema_editor):
    """
    Pega todos os ETPs com o status antigo 'AGUARDANDO_REVISAO'
    e atualiza para o novo status 'AGUARDANDO_ANALISE'.
    """
    # Usamos apps.get_model para pegar a versão histórica do modelo
    ETP = apps.get_model('contratacoes', 'ETP')
    ETP.objects.filter(status='AGUARDANDO_REVISAO').update(status='AGUARDANDO_ANALISE')

def atualizar_status_para_tras(apps, schema_editor):
    """
    Se precisarmos reverter a migração, faz o caminho contrário.
    """
    ETP = apps.get_model('contratacoes', 'ETP')
    ETP.objects.filter(status='AGUARDANDO_ANALISE').update(status='AGUARDANDO_REVISAO')


class Migration(migrations.Migration):

    dependencies = [
    ('contratacoes', '0002_initial'), 
    ]

    operations = [
        # Aqui instruímos o Django a rodar nosso script
        migrations.RunPython(atualizar_status_para_frente, reverse_code=atualizar_status_para_tras),
    ]