# Generated by Django 5.2.4 on 2025-09-02 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratacoes', '0003_migrar_status_etp'),
        ('core', '0002_fornecedor'),
        ('licitacoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(max_length=50, verbose_name='Número do Contrato')),
                ('ano_contrato', models.IntegerField(verbose_name='Ano do Contrato')),
                ('objeto', models.TextField(verbose_name='Objeto do Contrato')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Total do Contrato (R$)')),
                ('data_assinatura', models.DateField(verbose_name='Data de Assinatura')),
                ('data_inicio_vigencia', models.DateField(verbose_name='Início da Vigência')),
                ('data_fim_vigencia', models.DateField(verbose_name='Fim da Vigência')),
                ('status', models.CharField(choices=[('VIGENTE', 'Vigente'), ('ENCERRADO', 'Encerrado'), ('CANCELADO', 'Cancelado')], default='VIGENTE', max_length=20, verbose_name='Status do Contrato')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('contratado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='core.fornecedor', verbose_name='Fornecedor Contratado')),
                ('licitacao_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_gerados', to='licitacoes.edital', verbose_name='Licitação de Origem')),
                ('processo_vinculado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='core.processo', verbose_name='Processo Vinculado')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-ano_contrato', '-numero_contrato'],
                'unique_together': {('numero_contrato', 'ano_contrato')},
            },
        ),
    ]
