# Generated by Django 5.2.4 on 2025-09-04 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudespConfiguracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio_codigo_audesp', models.IntegerField(help_text='Código do município conforme tabela do AUDESP/TCE-SP.', verbose_name='Código do Município (AUDESP)')),
                ('entidade_codigo_audesp', models.IntegerField(help_text='Código da entidade ou órgão da prefeitura conforme tabela do AUDESP/TCE-SP.', verbose_name='Código da Entidade (AUDESP)')),
            ],
            options={
                'verbose_name': 'Configuração AUDESP',
                'verbose_name_plural': 'Configurações AUDESP',
            },
        ),
        migrations.CreateModel(
            name='SubmissaoAudesp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('data_submissao', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora da Ação')),
                ('status_tce', models.CharField(choices=[('PENDENTE', 'Pendente de Envio'), ('ENVIADO', 'Enviado, Aguardando Processamento'), ('ACEITO', 'Aceite pelo TCE'), ('REJEITADO', 'Rejeitado pelo TCE com Erros'), ('ERRO_ENVIO', 'Erro na Comunicação')], default='PENDENTE', max_length=20, verbose_name='Status no TCE')),
                ('resposta_tce', models.TextField(blank=True, null=True, verbose_name='Resposta/Log de Erros do TCE')),
                ('protocolo_tce', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número do Protocolo no TCE')),
                ('data_resposta_tce', models.DateTimeField(blank=True, null=True, verbose_name='Data da Resposta do TCE')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('usuario_responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável pelo Envio')),
            ],
            options={
                'verbose_name': 'Submissão AUDESP',
                'verbose_name_plural': 'Submissões AUDESP',
                'ordering': ['-data_submissao'],
            },
        ),
    ]
