# Generated by Django 5.2.4 on 2025-08-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracao_audesp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audespajustecontratual',
            name='tipo_objeto_contrato',
            field=models.IntegerField(blank=True, choices=[(1, 'Aquisição de Bens'), (2, 'Prestação de Serviços'), (3, 'Obras e Serviços de Engenharia'), (4, 'Locação de Imóveis'), (5, 'Alienação de Bens'), (6, 'Concessão de Uso'), (7, 'Permissão de Uso'), (8, 'Doação'), (9, 'Acordos de Cooperação'), (10, 'Outros Contratos Administrativos'), (11, 'Gestão e Manutenção'), (12, 'Tecnologia da Informação'), (13, 'Comunicação e Publicidade'), (14, 'Eventos e Festividades'), (15, 'Transporte e Logística'), (16, 'Saúde e Assistência Social'), (17, 'Educação e Cultura'), (18, 'Meio Ambiente'), (19, 'Urbanismo e Infraestrutura'), (20, 'Segurança e Vigilância'), (21, 'Serviços de Consultoria'), (22, 'Alimentos e Bebidas'), (23, 'Vestuário e Equipamentos'), (24, 'Combustíveis e Lubrificantes'), (25, 'Materiais de Consumo'), (26, 'Equipamentos e Máquinas'), (27, 'Softwares e Sistemas'), (28, 'Veículos'), (29, 'Mobiliário')], null=True, verbose_name='Tipo de Objeto do Ajuste (PNCP)'),
        ),
    ]
