# Generated by Django 5.2.4 on 2025-08-06 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('integracao_audesp', '0002_alter_audespajustecontratual_tipo_objeto_contrato'),
        ('licitacoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudespEditalDetalhado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.IntegerField(verbose_name='Município (Cód. AUDESP)')),
                ('entidade', models.IntegerField(verbose_name='Entidade (Cód. AUDESP)')),
                ('codigo_edital_audesp', models.CharField(max_length=25, verbose_name='Código Edital (AUDESP)')),
                ('retificacao', models.BooleanField(default=False, verbose_name='É Retificação (AUDESP)')),
                ('recurso_bid', models.IntegerField(choices=[(1, 'Sim'), (2, 'Não'), (3, 'Não se aplica')], verbose_name='Recursos BID Envolvidos')),
                ('abertura_pre_qualificacao_bid', models.IntegerField(blank=True, choices=[(1, 'Houve Objeção'), (2, 'Não Houve Objeção'), (3, 'Não se aplica')], null=True, verbose_name='Objeção BID Abertura Pré-qualificação')),
                ('edital_pre_qualificacao_bid', models.IntegerField(blank=True, choices=[(1, 'Houve Objeção'), (2, 'Não Houve Objeção'), (3, 'Não se aplica')], null=True, verbose_name='Objeção BID Edital Pré-qualificação')),
                ('julgamento_pre_qualificacao_bid', models.IntegerField(blank=True, choices=[(1, 'Houve Objeção'), (2, 'Não Houve Objeção'), (3, 'Não se aplica')], null=True, verbose_name='Objeção BID Julgamento Pré-qualificação')),
                ('edital_2_fase_bid', models.IntegerField(blank=True, choices=[(1, 'Houve Objeção'), (2, 'Não Houve Objeção'), (3, 'Não se aplica')], null=True, verbose_name='Objeção BID Edital 2ª Fase')),
                ('julgamento_propostas_bid', models.IntegerField(blank=True, choices=[(1, 'Houve Objeção'), (2, 'Não Houve Objeção'), (3, 'Não se aplica')], null=True, verbose_name='Objeção BID Julgamento Propostas')),
                ('julgamento_negociacao_bid', models.IntegerField(blank=True, choices=[(1, 'Houve Objeção'), (2, 'Não Houve Objeção'), (3, 'Não se aplica')], null=True, verbose_name='Objeção BID Julgamento Negociação Final')),
                ('tipo_natureza', models.IntegerField(choices=[(1, 'Compras'), (2, 'Serviços'), (3, 'Obras'), (4, 'Alienações'), (5, 'Concessões'), (6, 'Permissões'), (7, 'Doações'), (8, 'Outros')], verbose_name='Tipo de Natureza')),
                ('viabilidade_contratacao', models.IntegerField(blank=True, choices=[(1, 'Sim'), (2, 'Não'), (3, 'Não se aplica')], null=True, verbose_name='Viabilidade da Contratação')),
                ('interposicao_recurso', models.IntegerField(choices=[(1, 'Sim'), (2, 'Não'), (3, 'Não se aplica')], verbose_name='Houve Interposição de Recurso')),
                ('audiencia_publica', models.IntegerField(blank=True, choices=[(1, 'Sim'), (2, 'Não'), (3, 'Não se aplica')], null=True, verbose_name='Houve Audiência Pública')),
                ('exigencia_garantia_licitantes', models.IntegerField(choices=[(1, 'Sim'), (2, 'Não'), (3, 'Não se aplica')], verbose_name='Exigência de Garantia para Licitantes')),
                ('percentual_valor_garantia', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Percentual do Valor da Garantia')),
                ('exigencia_amostra', models.IntegerField(choices=[(1, 'Sim'), (2, 'Não'), (3, 'Não se aplica')], verbose_name='Exigência de Amostra')),
                ('quitacao_tributos_federais', models.BooleanField(verbose_name='Exige Quitação Tributos Federais')),
                ('quitacao_tributos_estaduais', models.BooleanField(verbose_name='Exige Quitação Tributos Estaduais')),
                ('quitacao_tributos_municipais', models.BooleanField(verbose_name='Exige Quitação Tributos Municipais')),
                ('exigencia_visita_tecnica', models.IntegerField(blank=True, choices=[(1, 'Sim'), (2, 'Não'), (3, 'Não se aplica')], null=True, verbose_name='Exigência de Visita Técnica')),
                ('exigencia_curriculo', models.BooleanField(verbose_name='Exigência de Currículo (Visita Técnica)')),
                ('exigencia_visto_crea', models.BooleanField(verbose_name='Exigência de Visto CREA/SP (Outros Estados)')),
                ('declaracao_recursos_orcamentarios', models.BooleanField(verbose_name='Declaração de Recursos Orçamentários')),
                ('fonte_recursos_contratacao_detalhada', models.JSONField(blank=True, default=list, help_text='Lista de fontes de recursos que constam na declaração da existência de recursos orçamentários para a contratação (array de números).', null=True, verbose_name='Fontes de Recursos da Contratação')),
                ('contratacao_conduzida', models.BooleanField(verbose_name='Contratação Conduzida por Agente/Comissão')),
                ('cpfs_condutores', models.JSONField(blank=True, default=list, help_text="Lista de CPFs dos condutores da licitação (array de objetos com 'cpfCondutor').", null=True, verbose_name='CPFs dos Condutores')),
                ('exigencia_indices_economicos', models.IntegerField(choices=[(1, 'Sim'), (2, 'Não'), (3, 'Não se aplica')], verbose_name='Exigência de Índices Econômicos Mínimos')),
                ('indices_economicos', models.JSONField(blank=True, default=list, help_text='Lista de índices econômicos (array de objetos com tipoIndice, nomeIndice, valorIndice).', null=True, verbose_name='Índices Econômicos')),
                ('edital_principal', models.OneToOneField(blank=True, help_text='O Edital de licitação no sistema principal ao qual este detalhamento se refere.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audesp_edital_detalhado', to='licitacoes.edital', verbose_name='Edital Principal (SysGov)')),
                ('processo_vinculado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audesp_edital_detalhados', to='core.processo', verbose_name='Processo Principal (SysGov)')),
            ],
            options={
                'verbose_name': 'AUDESP Edital Detalhado',
                'verbose_name_plural': 'AUDESP Editais Detalhados',
                'ordering': ['-edital_principal__data_publicacao'],
            },
        ),
    ]
