# Generated by Django 5.2.4 on 2025-09-04 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratacoes', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_fiscal_numero', models.CharField(max_length=15, verbose_name='Número do Documento Fiscal (NF)')),
                ('documento_fiscal_valor', models.DecimalField(decimal_places=2, max_digits=17, verbose_name='Valor do Documento Fiscal')),
                ('documento_fiscal_data_emissao', models.DateField(verbose_name='Data de Emissão do Documento Fiscal')),
                ('codigo_ajuste', models.CharField(blank=True, max_length=20, verbose_name='Código do Ajuste/Empenho')),
                ('nota_empenho_numero', models.CharField(blank=True, max_length=35, verbose_name='Número da Nota de Empenho')),
                ('contrato_vinculado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_fiscais', to='contratacoes.contrato')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_fiscais', to='core.fornecedor')),
                ('processo_vinculado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_fiscais', to='core.processo')),
            ],
            options={
                'verbose_name': 'Documento Fiscal',
                'verbose_name_plural': 'Documentos Fiscais',
                'ordering': ['-documento_fiscal_data_emissao'],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_fiscal_valor_pago', models.DecimalField(decimal_places=2, max_digits=17, verbose_name='Valor Pago')),
                ('nota_fiscal_pagto_dt', models.DateField(verbose_name='Data Efetiva do Pagamento')),
                ('forma_pagamento', models.CharField(default='Transferência Bancária', max_length=100, verbose_name='Forma de Pagamento')),
                ('documento_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='financeiro.documentofiscal', verbose_name='Documento Fiscal Vinculado')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-nota_fiscal_pagto_dt'],
            },
        ),
        migrations.CreateModel(
            name='NotaEmpenho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_empenho', models.CharField(max_length=50, verbose_name='Número do Empenho')),
                ('ano_empenho', models.IntegerField(verbose_name='Ano do Empenho')),
                ('data_emissao', models.DateField(verbose_name='Data de Emissão')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor do Empenho (R$)')),
                ('descricao', models.TextField(verbose_name='Descrição/Histórico do Empenho')),
                ('status', models.CharField(choices=[('VALIDO', 'Válido'), ('CANCELADO', 'Cancelado'), ('LIQUIDADO', 'Liquidado')], default='VALIDO', max_length=20, verbose_name='Status do Empenho')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_empenho', to='contratacoes.contrato', verbose_name='Contrato Vinculado')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empenhos', to='core.fornecedor', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Nota de Empenho',
                'verbose_name_plural': 'Notas de Empenho',
                'ordering': ['-ano_empenho', '-data_emissao'],
                'unique_together': {('numero_empenho', 'ano_empenho')},
            },
        ),
    ]
