# Generated by Django 5.2.4 on 2025-09-02 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratacoes', '0004_contrato'),
        ('core', '0002_fornecedor'),
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaEmpenho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_empenho', models.CharField(max_length=50, verbose_name='Número do Empenho')),
                ('ano_empenho', models.IntegerField(verbose_name='Ano do Empenho')),
                ('data_emissao', models.DateField(verbose_name='Data de Emissão')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor do Empenho (R$)')),
                ('descricao', models.TextField(verbose_name='Descrição/Histórico do Empenho')),
                ('status', models.CharField(choices=[('VALIDO', 'Válido'), ('CANCELADO', 'Cancelado'), ('LIQUIDADO', 'Liquidado')], default='VALIDO', max_length=20, verbose_name='Status do Empenho')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_empenho', to='contratacoes.contrato', verbose_name='Contrato Vinculado')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empenhos', to='core.fornecedor', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Nota de Empenho',
                'verbose_name_plural': 'Notas de Empenho',
                'ordering': ['-ano_empenho', '-data_emissao'],
                'unique_together': {('numero_empenho', 'ano_empenho')},
            },
        ),
    ]
