# Generated by Django 5.2.4 on 2025-09-05 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_pagamento_processo_vinculado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='processo_vinculado',
        ),
    ]
