# Generated by Django 5.2.4 on 2025-09-02 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitacoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_abertura_sessao', models.DateTimeField(verbose_name='Data e Hora de Abertura da Sessão')),
                ('data_encerramento_sessao', models.DateTimeField(blank=True, null=True, verbose_name='Data e Hora de Encerramento')),
                ('status', models.CharField(choices=[('AGENDADO', 'Agendado'), ('ABERTO_PARA_LANCES', 'Aberto para Lances'), ('EM_DISPUTA', 'Em Disputa'), ('FINALIZADO', 'Finalizado'), ('SUSPENSO', 'Suspenso'), ('CANCELADO', 'Cancelado')], default='AGENDADO', max_length=30, verbose_name='Status da Sessão')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações e Ata da Sessão')),
                ('edital', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pregao', to='licitacoes.edital', verbose_name='Edital de Referência')),
                ('pregoeiro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pregoes_conduzidos', to=settings.AUTH_USER_MODEL, verbose_name='Pregoeiro Responsável')),
            ],
            options={
                'verbose_name': 'Pregão (Sessão de Disputa)',
                'verbose_name_plural': 'Pregões (Sessões de Disputa)',
                'ordering': ['-data_abertura_sessao'],
            },
        ),
    ]
