# Generated by Django 5.2.4 on 2025-09-02 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fornecedor'),
        ('licitacoes', '0002_pregao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipanteLicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_credenciamento', models.DateTimeField(auto_now_add=True, verbose_name='Data de Credenciamento')),
                ('desclassificado', models.BooleanField(default=False, verbose_name='Desclassificado?')),
                ('motivo_desclassificacao', models.TextField(blank=True, null=True, verbose_name='Motivo da Desclassificação')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes', to='core.fornecedor', verbose_name='Fornecedor Licitante')),
                ('pregao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='licitacoes.pregao', verbose_name='Pregão')),
            ],
            options={
                'verbose_name': 'Participante da Licitação',
                'verbose_name_plural': 'Participantes da Licitação',
                'ordering': ['data_credenciamento'],
                'unique_together': {('pregao', 'fornecedor')},
            },
        ),
        migrations.CreateModel(
            name='Lance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_lance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor do Lance')),
                ('data_lance', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora do Lance')),
                ('aceito', models.BooleanField(default=False, verbose_name='Lance Vencedor?')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lances', to='licitacoes.itemlicitado', verbose_name='Item do Edital')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lances', to='licitacoes.participantelicitacao', verbose_name='Participante')),
            ],
            options={
                'verbose_name': 'Lance',
                'verbose_name_plural': 'Lances',
                'ordering': ['item', 'valor_lance'],
            },
        ),
    ]
